using composite action in access workflow

diff --git a/.github/workflows/access.yaml b/.github/workflows/access.yaml
--- a/.github/workflows/access.yaml
+++ b/.github/workflows/access.yaml
@@ -26,28 +26,30 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+      - name: Use Composite Action
+        uses: ../../.github/actions/cli-setup.yaml
+      # - name: Checkout
+      #   uses: actions/checkout@v3
 
-      - name: Download the toolkit-cli
-        run: |
-          set -euo pipefail
-          curl --fail --output toolkit-cli.zip $TOOLKIT_CLI_DOWNLOAD_URL
-          unzip -jd install toolkit-cli.zip
+      # - name: Download the toolkit-cli
+      #   run: |
+      #     set -euo pipefail
+      #     curl --fail --output toolkit-cli.zip $TOOLKIT_CLI_DOWNLOAD_URL
+      #     unzip -jd install toolkit-cli.zip
 
-      - name: Add toolkit to PATH
-        run: readlink -f install >> $GITHUB_PATH
+      # - name: Add toolkit to PATH
+      #   run: readlink -f install >> $GITHUB_PATH
 
-      - name: Write Snowflake private key
-        run: |
-          (umask  077 ; echo $SNOWFLAKE_PRIVATE_KEY_PEM | base64 --decode > /tmp/snowflake_key.p8)
-          echo "SNOWFLAKE_PRIVATE_KEY_FILE=/tmp/snowflake_key.p8" >> $GITHUB_ENV
+      # - name: Write Snowflake private key
+      #   run: |
+      #     (umask  077 ; echo $SNOWFLAKE_PRIVATE_KEY_PEM | base64 --decode > /tmp/snowflake_key.p8)
+      #     echo "SNOWFLAKE_PRIVATE_KEY_FILE=/tmp/snowflake_key.p8" >> $GITHUB_ENV
 
-      - name: Set up Java
-        uses: actions/setup-java@v3
-        with:
-          java-version: 11
-          distribution: corretto
+      # - name: Set up Java
+      #   uses: actions/setup-java@v3
+      #   with:
+      #     java-version: 11
+      #     distribution: corretto
 
       - name: Scan snowflake
         run: toolkit access scan snowflake
