added composite action to provision

diff --git a/.github/workflows/provision.yaml b/.github/workflows/provision.yaml
--- a/.github/workflows/provision.yaml
+++ b/.github/workflows/provision.yaml
@@ -12,9 +12,9 @@ on:
     branches:
       - master
 
-defaults:
-  run:
-    working-directory: tools/provision
+# defaults:
+#   run:
+#     working-directory: tools/provision
 
 env:
   TOOLKIT_AUTH_TOKEN: ${{ secrets.toolkit_auth_token }}
@@ -31,42 +31,53 @@ jobs:
 
     steps:
       - name: Checkout
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
-      - name: Download the toolkit-cli
-        shell: bash
-        run: |
-          set -euo pipefail
+      - name: Use Composite Action
+        uses: ./.github/actions/common-setup
+      # - name: Checkout
+      #   uses: actions/checkout@v3
 
-          curl --fail --output toolkit-cli.zip $TOOLKIT_CLI_DOWNLOAD_URL
-          unzip -jd install toolkit-cli.zip
+      # - name: Download the toolkit-cli
+      #   shell: bash
+      #   run: |
+      #     set -euo pipefail
 
-      - name: Run admin shell
-        shell: bash
-        run: readlink -f install >> $GITHUB_PATH
+      #     curl --fail --output toolkit-cli.zip $TOOLKIT_CLI_DOWNLOAD_URL
+      #     unzip -jd install toolkit-cli.zip
 
-      - name: Write Snowflake private key
-        shell: bash
-        run: |
-          (umask  077 ; echo $SNOWFLAKE_PRIVATE_KEY_PEM | base64 --decode > /tmp/snowflake_key.p8)
-          echo "SNOWFLAKE_PRIVATE_KEY_FILE=/tmp/snowflake_key.p8" >> $GITHUB_ENV
+      # - name: Run admin shell
+      #   shell: bash
+      #   run: readlink -f install >> $GITHUB_PATH
 
-      - name: Set up Java
-        uses: actions/setup-java@v3
-        with:
-          java-version: 11
-          distribution: corretto
+      # - name: Write Snowflake private key
+      #   shell: bash
+      #   run: |
+      #     (umask  077 ; echo $SNOWFLAKE_PRIVATE_KEY_PEM | base64 --decode > /tmp/snowflake_key.p8)
+      #     echo "SNOWFLAKE_PRIVATE_KEY_FILE=/tmp/snowflake_key.p8" >> $GITHUB_ENV
+
+      # - name: Set up Java
+      #   uses: actions/setup-java@v3
+      #   with:
+      #     java-version: 11
+      #     distribution: corretto
 
       - name: Create metadata
         shell: bash
-        run: toolkit provision init --metadata
+        run: |
+          cd tools/provision
+          toolkit provision init --metadata
 
       - name: Plan on pull request
         if: github.event_name == 'pull_request'
         shell: bash
-        run: toolkit provision apply --plan
+        run: |
+          cd tools/provision
+          toolkit provision apply --plan
 
       - name: Apply changes on merge to master
         shell: bash
-        run: toolkit provision apply
+        run: |
+          cd tools/provision
+          toolkit provision apply
         if: github.event_name == 'push'
